image: "rust:latest"
before_script:
  - rustup component add clippy


test:
  script:
    - rustc --version && cargo --version
    - cargo clippy -- -D warnings
    - cargo test --workspace --verbose
